version: "3"
services:
    web:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - SqlServer
    SqlServer:
        image: 'microsoft/mssql-server-linux'
        environment:
            SA_PASSWORD: 'demo123$$!'
            ACCEPT_EULA: 'Y'