# FROM microsoft/aspnetcore-build:lts
# COPY . /app
# WORKDIR /app
# RUN ["dotnet", "restore"]
# RUN ["dotnet", "build"]
# EXPOSE 80/tcp
# RUN chmod +x ./entrypoint.sh
# CMD /bin/bash ./entrypoint.sh

FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY src/*.csproj ./
RUN dotnet restore

# copy everything else and build
COPY src/ ./
RUN dotnet publish -c Release -o out


# build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .


ENTRYPOINT ["dotnet", "HelloWebApi.dll"]

# FROM microsoft/aspnetcore-build:2.0 

# COPY src/ /app

# WORKDIR /app

# RUN ["dotnet", "restore"]

# RUN ["dotnet", "build"]

# COPY entrypoint.sh /app/entrypoint.sh

# RUN apt-get update && apt-get install -y dos2unix

# RUN dos2unix /app/entrypoint.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

# RUN chmod +x ./entrypoint.sh

# CMD /bin/bash ./entrypoint.sh