FROM microsoft/aspnetcore-build:2.0 

# WORKDIR /vsdbg

WORKDIR /app

RUN apt-get update

RUN apt-get install curl unzip -y

RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

 
ENTRYPOINT ["tail", "-f", "/dev/null"]