version: "2"
services:
    web:
        container_name: 'webui'
        build: 
          context: .
          dockerfile: dockerfile
        ports:
            - "8000:80"
        depends_on:
            - SqlServer
        expose:
            - "1433"
        environment:
            SQLSERVER_HOST: 172.16.238.10
            SQLSERVER_SA_PASSWORD: 'demo123$$!'
        networks:
            - app_net
    SqlServer:
        container_name: 'SqlServer'
        image: 'microsoft/mssql-server-linux'
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: 'demo123$$!'
            ACCEPT_EULA: 'Y'
        volumes:
            - mssql-server-linux-data:/var/opt/mssql/data
        networks:
            app_net:
                ipv4_address: 172.16.238.10
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24

volumes:
  mssql-server-linux-data:
