# FROM microsoft/aspnetcore-build:lts
# COPY . /app
# WORKDIR /app
# RUN ["dotnet", "restore"]
# RUN ["dotnet", "build"]
# EXPOSE 80/tcp
# RUN chmod +x ./entrypoint.sh
# CMD /bin/bash ./entrypoint.sh

# build stage
FROM microsoft/dotnet:2.0.0-sdk-jessie AS builder
WORKDIR /src
COPY src/ .
RUN dotnet restore; dotnet build; dotnet publish

# final image stage
FROM microsoft/dotnet:2.0.0-runtime-jessie
WORKDIR /dotnetapp
EXPOSE 80/tcp
COPY --from=builder /src/bin/Debug/netcoreapp2.0/publish .
# COPY entrypoint.sh ./entrypoint.sh
# RUN chmod +x ./entrypoint.sh
CMD ["dotnet", "HelloWebApi.dll"]

