
# FROM microsoft/dotnet:2.0.0-sdk-nanoserver
# WORKDIR /src
# COPY src/ .
# RUN dotnet restore; dotnet build; dotnet publish
# CMD ["dotnet", "run"]

#dotnet build
#dotnet publish

# FROM microsoft/aspnetcore:2.0.0
# WORKDIR /dotnetapp
# COPY ./src/bin/Debug/netcoreapp1.1/publish .
# CMD ["dotnet", "HelloWebApi.dll"]

### MULTI STAGE BUILD

# build stage
FROM microsoft/dotnet:2.0.0-sdk-nanoserver AS builder
WORKDIR /src
COPY src/ .
RUN dotnet restore; dotnet build; dotnet publish

# final image stage
FROM microsoft/aspnetcore:2.0.0
WORKDIR /dotnetapp
COPY --from=builder /src/bin/Debug/netcoreapp2.0/publish .
ENV ASPNETCORE_URLS http://+:80
EXPOSE 80
CMD ["dotnet", "HelloWebApi.dll"]
