# FROM microsoft/dotnet:2.0.0-sdk-nanoserver AS builder
# WORKDIR /src
# COPY src/ .
# RUN dotnet restore; dotnet build
# CMD ["dotnet", "run"]

# FROM microsoft/dotnet:1.1-runtime-nanoserver
# WORKDIR /dotnetapp
# COPY ./src/bin/Debug/netcoreapp1.1/publish .
# CMD ["dotnet", "HelloWorld.NetCore.dll"]


# build stage
FROM microsoft/dotnet:2.0.0-sdk-nanoserver AS builder
WORKDIR /src
COPY src/ .
RUN dotnet restore; dotnet build; dotnet publish

# final image stage
FROM microsoft/dotnet:2.0.0-runtime-nanoserver
WORKDIR /dotnetapp
COPY --from=builder /src/bin/Debug/netcoreapp2.0/publish .
CMD ["dotnet", "HelloWorld.NetCore.dll"]
